# GitHub Actions workflow to automatically build and test.
name: 'Build'

on:
  push:
    branches: ['main']
    paths-ignore:
      - '**/README.md'
  pull_request:
    paths-ignore:
      - '**/README.md'

# Cancel in progress workflows on pull_requests.
# https://docs.github.com/en/actions/using-jobs/using-concurrency#example-using-a-fallback-value
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  JAVA_VERSION: 21

permissions:
  issues: write
  contents: write

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4

      - name: 'Set up Java ${{ env.JAVA_VERSION }}'
        uses: actions/setup-java@v4
        with:
          java-version: '${{ env.JAVA_VERSION }}'
          distribution: 'zulu'
      - name: 'Setup Gradle'
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: ${{ github.event_name == 'pull_request' }}
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"
      - name: 'Make gradlew executable'
        run: chmod +x ./gradlew
      - name: 'Validate Gradle wrapper'
        uses: gradle/actions/wrapper-validation@v4

      - name: Restore Ignition Image Cache if it exists
        id: cache-docker-ignition
        uses: actions/cache@v4
        with:
          path: ci/cache/docker/ignition
          key: cache-docker-ignition

      - name: Update Ignition Image Cache if cache miss
        if: steps.cache-docker-ignition.outputs.cache-hit != 'true'
        run: docker pull inductiveautomation/ignition:8.1.33 && mkdir -p ci/cache/docker/ignition && docker image save inductiveautomation/ignition:8.1.33 --output ./ci/cache/docker/ignition/ignition-8.1.33.tar

      - name: Use Ignition Image Cache if cache hit
        if: steps.cache-docker-ignition.outputs.cache-hit == 'true'
        run: docker image load --input ./ci/cache/docker/ignition/ignition-8.1.33.tar

      - name: 'Build'
        run: ./gradlew --scan build
